# from freecode camp

In [1]:
import numpy as np

**THe basis**

In [2]:
a=np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
b=np.array([[9.0,7.0,5.0,3.0],[8.0,6.0,4.0,2.0]])
print(b)

[[9. 7. 5. 3.]
 [8. 6. 4. 2.]]


In [4]:
#get dimensions
print(a.ndim)
print(b.ndim)

1
2


In [5]:
#get shape
print(a.shape)
print(b.shape)

(3,)
(2, 4)


In [6]:
#get type
print(a.dtype)
print(b.dtype)

int64
float64


In [7]:
#define data type
c=np.array([1,2,3], np.int8)
d=np.array([4,5,6,7], dtype='int16')

In [8]:
print(c.dtype)
print(d.dtype)

int8
int16


In [9]:
#get size
print(a.itemsize) #8 cuz 64 bits= 8bytes by default
print(b.itemsize) #8 as 64 bits 
print(c.itemsize) #1 cuz 8bits so 8 bits = 1 byte
print(d.itemsize) #2 cuz 16 bits = 2 bytes 

8
8
1
2


In [10]:
#get no. of elements
print(a.size)
print(b.size)
print(c.size)
print(d.size)

3
8
3
4


In [11]:
#get total size
print(a.size * a.itemsize)
print(b.size * b.itemsize)
print(c.size * c.itemsize)
print(d.size * d.itemsize)
# OR
print(a.nbytes)
print(b.nbytes)
print(c.nbytes)
print(d.nbytes)

24
64
3
8
24
64
3
8


# Accessing/Changing specific elements, rows, columns, etc.

In [12]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)
print(a.shape)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
(2, 7)


In [13]:
#get a specific element [row, column]
print(a[0,0])
print(a[1,5])
print(a[0,6])
print(a[1,-1])
print(a[1,-2])
print(a[-2,1])

1
13
7
14
13
2


In [14]:
#Get a specific row
print(a[0, : ]) # row = 0 , column = : means all

[1 2 3 4 5 6 7]


In [15]:
#get a specific column
print(a[ :, 4]) #row= : means all , column = 4

[ 5 12]


In [16]:
# Getting a little more fancy [starting index: endindex: stepsize]
print(a[0, 1:6:2]) # [row=0, column= 1:6:2]
print(a[0, 1:-1:2])
print(a[1, 1:6:1])

[2 4 6]
[2 4 6]
[ 9 10 11 12 13]


In [17]:
#changing original value
a[1,4]=20 #particular element at 1,4
print(a)
a[:,2]=5 #all rows where column=2 i.e. 0,2 and 1,2
print(a)
a[1,:]=10 # all at row 1 all columns = 10
print(a)
a[:,2]=[100,200] 
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 20 13 14]]
[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 20 13 14]]
[[ 1  2  5  4  5  6  7]
 [10 10 10 10 10 10 10]]
[[  1   2 100   4   5   6   7]
 [ 10  10 200  10  10  10  10]]


 # 3d examples
 

In [18]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [19]:
#get specific elements (worl outside in)
print(b[0,1,1]) #outside to inside []
print(b[0,0,0])
print(b[0,0,1])
print(b[0,1,0])
print(b[0,1,1])
print(b[1,0,0])
print(b[1,0,1])
print(b[1,1,0])
print(b[1,1,1])

4
1
2
3
4
5
6
7
8


In [20]:
print(b[:,1,:])
print(b[1,:,:])
print(b[0,:,1])

[[3 4]
 [7 8]]
[[5 6]
 [7 8]]
[2 4]


In [21]:
 #replace with new value
b[:,1,:]=[[9,9],[8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


# Initializing different types of arrays

In [22]:
# All 0s matrix
print(np.zeros((2,3)))
print(np.zeros((2,3,4)))
print(np.zeros((2,3,3,2)))

[[0. 0. 0.]
 [0. 0. 0.]]
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
[[[[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]]


 [[[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]]]


In [23]:
#all 1s marrix
np.ones((4,2,3),dtype='int64')

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

In [24]:
# Any other number
print(np.full((2,2),99))

[[99 99]
 [99 99]]


In [25]:
print(np.full(b.shape,4))
#or
print(np.full_like(b,4))

[[[4 4]
  [4 4]]

 [[4 4]
  [4 4]]]
[[[4 4]
  [4 4]]

 [[4 4]
  [4 4]]]


In [26]:
# Random decimal numbers
print(np.random.rand(4,2))#here we dont need extra braces ((4,2)) as in previous initializations
print(np.random.rand(4,2,3))

[[0.55385846 0.16809607]
 [0.13545599 0.82122823]
 [0.91601519 0.83665502]
 [0.49155563 0.08083546]]
[[[0.55266516 0.66755307 0.39974614]
  [0.0161021  0.61761462 0.97505226]]

 [[0.99228469 0.66708965 0.11626619]
  [0.55006936 0.31660523 0.97820607]]

 [[0.75193202 0.06507995 0.35541772]
  [0.29049029 0.09757387 0.14781476]]

 [[0.61884138 0.8854071  0.31972527]
  [0.09107258 0.90955832 0.80772605]]]


In [27]:
#random decimals with shape of already defined arrays
print(np.random.random_sample(b.shape))

[[[0.81204678 0.98469159]
  [0.66384749 0.49830692]]

 [[0.09076692 0.4852344 ]
  [0.28434435 0.57922909]]]


In [28]:
# Random Integer Values
print(np.random.randint(3,size=(4,2))) # prints number from 0-3
print(np.random.randint(3,8,size=(4,4))) # prints number from 3-7


[[1 2]
 [1 2]
 [2 0]
 [0 1]]
[[6 4 3 5]
 [5 5 3 5]
 [5 7 5 3]
 [7 7 3 7]]


In [29]:
# indentity matrix (it is a square matrix so row=column)
print(np.identity(5))
print(np.identity(2))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[1. 0.]
 [0. 1.]]


In [30]:
# Repeating an array n times
arr = np.array([1,2,3]) # 1d array
r1=np.repeat(arr,3)
print(r1)

arr = np.array([[1,2,3]]) # 2d array
r1=np.repeat(arr,3,axis=0) 
print(r1)

arr = np.array([[1,2,3]]) # 2d array
r1=np.repeat(arr,3, axis=1)
print(r1)

[1 1 1 2 2 2 3 3 3]
[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[1 1 1 2 2 2 3 3 3]]


In [31]:
''''[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]''' 
# create this array 
output=np.ones((5,5))
print(output)

z=np.zeros((3,3))
z[1,1]=9
print(z)

output[1:4,1:4]=z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


# BE CAREFUL WHEN COPYING ARRAYS!!!

In [32]:
a=np.array([1,2,3])
b=a #WE DIDN'T TELL THE NUMPY TO MAKE A COPY OF A, B=A means a variable named b points to the same thing as a does
print(b)
b[0]=100 #if i want to change the first element of b
print(b) # no problem here as we got b as same as a but the first element as our wish
print(a) # but here a is also changed when we changed b[0]
#since be is pointing to the same exact thing as a, so when we changed a value of b then it also changed a

[1 2 3]
[100   2   3]
[100   2   3]


In [33]:
# Actual copying:
a=np.array([1,2,3])
b=a.copy() # b is now a copy of a - copying the content of a in b
print(b)
b[0]=100 # we changed a value in b
print(b) # updated b is printed
print(a) # a is printed as it is not like as in above case, as a seperate b is created as a copy of a

[1 2 3]
[100   2   3]
[1 2 3]


# Mathematics

In [34]:
# numpy allows us to do element wise addition subtraction and other mathematical operations
a=np.array([1,2,3,4]) 
print(a)

[1 2 3 4]


In [35]:
a+2 # addtion of 2 to each elements
# no change to original a i.e. a= 1,2,3,4

array([3, 4, 5, 6])

In [36]:
a-=2 # sbtraction of 2 from each element
#here oroiginal a is changed i.e. a = -1, 0, 1, 2
print(a)

[-1  0  1  2]


In [37]:
print(a/2) # divides each element by 2
# no change to previous a i.e a= -1,0,1,2

[-0.5  0.   0.5  1. ]


In [38]:
a=a*2
# now a is agian changed a=-2,0,2,4
print(a)

[-2  0  2  4]


In [39]:
print(a**2) # a**2 = a^2

[ 4  0  4 16]


In [40]:
a=np.array([1,2,3,4]) 
b=np.array([0,1,4,9])
print(a+b)
print(a-b)
print(b-a)
print(a*b)
print(b/a)
print(a**b) #a^b

[ 1  3  7 13]
[ 1  1 -1 -5]
[-1 -1  1  5]
[ 0  2 12 36]
[0.         0.5        1.33333333 2.25      ]
[     1      2     81 262144]


In [41]:
# Take the sin
val=np.array([1,2,3,4])
print(np.sin(val))# when val is number like 1 2 3 4 then it return sin(1 rad), sin(2 rad), sin(3 rad)...

value=np.array([0,np.pi/4,np.pi/2,np.pi]) # here the values are degree
print(np.sin(value))

[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[0.00000000e+00 7.07106781e-01 1.00000000e+00 1.22464680e-16]


In [42]:
# Take cos
print(np.cos(val)) # since val has numbers it treats those numbers as radian
print(np.cos(value)) # value has degree

[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]
[ 1.00000000e+00  7.07106781e-01  6.12323400e-17 -1.00000000e+00]


# Linear Algebra

In [43]:
# In linear Algebra there is not element wise operation as in above cases
#MATRIX MULTIPLICATION
a = np.ones((2,3))
print(a)

b = np.full((3,3),2)
print(b)

# a*b is wrong for matrix multiplication here as they are of different sizes and a*b would do element wise multiplication as above
AB = np.matmul(a,b)
print(AB)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2 2]
 [2 2 2]
 [2 2 2]]
[[6. 6. 6.]
 [6. 6. 6.]]


In [44]:
# DTERMINANT OF MATRIX
c = np.identity(3)
det = np.linalg.det(c)
print(det)
# print(np.linalg.det(a)) -> not possible, det is only for square matrix
d = np.full((4,4),5)
print(np.linalg.det(d))

1.0
0.0


In [45]:
# there are also functions in linear algebra to find
# Determinant
# Trace
# Singular vector decomposition
# Eigen values
# Matrix norm
# Inverse
# etc.

# Statistics

In [46]:
# max min mean median mode deviation etc.
stats = np.array([[1,2,3],[4,5,6]])
print(stats)


[[1 2 3]
 [4 5 6]]


In [47]:
#MIN
print(np.min(stats))
print(np.min(stats,axis=1)) # row wise min
print(np.min(stats,axis=0)) # column wise min


1
[1 4]
[1 2 3]


In [48]:
#MAX
print(np.max(stats)) 
print(np.max(stats, axis=1)) # row wise max
print(np.max(stats, axis=0))# column wise max

6
[3 6]
[4 5 6]


In [49]:
# MEAN
print(np.mean(stats))
print(np.mean(stats,axis=1)) # row wise mean
print(np.mean(stats,axis=0)) # column wise mean

3.5
[2. 5.]
[2.5 3.5 4.5]


In [50]:
#SUM
print(np.sum(stats))
print(np.sum(stats, axis=1)) # sum of row
print(np.sum(stats, axis=0)) # sum of column

21
[ 6 15]
[5 7 9]


# Reorganixing Arrays

In [51]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)
print(before.shape)
# if we want to change the shape of this matrix, i.e. order of matrix
after = before.reshape(8,1) # now the order is 8 by 1
print(after)
after = before.reshape(4,2) # now the order is 4 by 2 
print(after)
after= before.reshape(2,2,2) # now the size is 2 by 2 by 2 3d array
print(after)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [52]:
# VERTICLLY STACKING VECTORS OR MATRICES
# for vertical no. of columns should be equal
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

print(np.vstack([v1,v2]))
print(np.vstack([v1,v2,v2,v2]))
print(np.vstack([v1,v2,v1]))

[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]
 [5 6 7 8]]
[[1 2 3 4]
 [5 6 7 8]
 [1 2 3 4]]


In [53]:
# HORIZONTAL STACKS
# for horizontal no. of rows should be equal
h1 = np.ones((2,4))
h2 = np.zeros((2,3))

print(np.hstack([h1,h2]))

[[1. 1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 1. 0. 0. 0.]]


# Miscellaneous

### Load from  data file

In [54]:
filedata = np.genfromtxt('trial.txt',delimiter=',') # file must have same no. of columns in all rows as in matrix
# genfromtxt returns float type by default so while printing filedata it is printed in float format
print(filedata)
print(filedata.dtype)
print(filedata.astype('int64')) # to convert all data into int64 type we can also change to int8, int32...

filedata = np.genfromtxt('trial.txt', delimiter=',',dtype='int64')
# here we have defined it to have int64 data type so the data type will be int64 if anything is not mentioned then by default it will return float64
print(filedata) 
print(filedata.dtype)

[[  1.  13.  21.  11. 196.  75.   4.   3.  34.   6.]
 [  8.  99.  67.  43.  23.  76.  89.  12.  45.  56.]
 [ 78.  98.  87.  65.  54.  43.  32.  15.  16.  59.]]
float64
[[  1  13  21  11 196  75   4   3  34   6]
 [  8  99  67  43  23  76  89  12  45  56]
 [ 78  98  87  65  54  43  32  15  16  59]]
[[  1  13  21  11 196  75   4   3  34   6]
 [  8  99  67  43  23  76  89  12  45  56]
 [ 78  98  87  65  54  43  32  15  16  59]]
int64


### Boolean Masking and Advanced Indexing

In [55]:
print(filedata>50)
print("\n")
print(filedata<50)
print("\n")
print(filedata==50)
print("\n")
print(filedata>=50)

[[False False False False  True  True False False False False]
 [False  True  True False False  True  True False False  True]
 [ True  True  True  True  True False False False False  True]]


[[ True  True  True  True False False  True  True  True  True]
 [ True False False  True  True False False  True  True False]
 [False False False False False  True  True  True  True False]]


[[False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]]


[[False False False False  True  True False False False False]
 [False  True  True False False  True  True False False  True]
 [ True  True  True  True  True False False False False  True]]


In [56]:
print(filedata[filedata>50])

print(np.any(filedata>50, axis=0)) # checks along the column if there is any >50 and returns true if any
print(np.any(filedata>50, axis = 1))# checks along the row and returns true if any is >50


print(np.all(filedata>50, axis=0)) # returns true only when all re >50 along the column else returns false
print(np.all(filedata>50, axis=1)) # returns true only if all the values are >50 along the rows else returns false

[196  75  99  67  76  89  56  78  98  87  65  54  59]
[ True  True  True  True  True  True  True False False  True]
[ True  True  True]
[False False False False False False False False False False]
[False False False]


In [57]:
# You can index with a list in Numpy
a = np.array([1,2,3,4,5,6,7,8,9])
print(a[[1,2,8]])


[2 3 9]


In [58]:
print((filedata>20) & (filedata<100))
print("\n")
print(~((filedata>20) & (filedata<100)))

[[False False  True False False  True False False  True False]
 [False  True  True  True  True  True  True False  True  True]
 [ True  True  True  True  True  True  True False False  True]]


[[ True  True False  True  True False  True  True False  True]
 [ True False False False False False False  True False False]
 [False False False False False False False  True  True False]]
