# Welcome to numpy tutorial


In [1]:
import numpy as np

In [2]:
myarr=np.array([1,2,3,4])

In [3]:
print(myarr)

[1 2 3 4]


In [4]:
myarr

array([1, 2, 3, 4])

In [5]:
myarr[1]

np.int64(2)

In [6]:
myarr.shape

(4,)

In [7]:
arr=np.array([1,2,3], np.int8)

In [8]:
arr

array([1, 2, 3], dtype=int8)

In [9]:
arr[0]

np.int8(1)

In [10]:
arr=np.array([[6,9,3,0]], np.int64)


In [11]:
arr.shape # output means it has 1 row and 4 columns 


(1, 4)

In [12]:
arr[0,2] #row=2 and colmn = 2 element

np.int64(3)

In [13]:
arr.dtype

dtype('int64')